name: Node.js CI

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install libraries
        run: sudo apt-get install -y libelf-dev libx11-dev libxcomposite-dev libxdamage-dev libxfixes-dev libxrandr-dev libxtst-dev
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run compile
      - uses: actions/upload-artifact@v3
        with:
          name: linux-fix.node
          path: build/Release/linux-fix.node
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/Release/linux-fix.node